# Generated by Django 4.2.16 on 2024-11-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TestUser',
        ),
    ]
