# Generated by Django 4.2.16 on 2024-12-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='routine_steps',
            field=models.IntegerField(),
        ),
    ]
