# Generated by Django 4.2.16 on 2024-12-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userinput_routine_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('prod_name', models.TextField()),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('ingredients', models.TextField()),
                ('review_no', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.TextField()),
                ('user_skin_type', models.JSONField()),
                ('user_skin_concerns', models.JSONField()),
            ],
        ),
    ]
