# Generated by Django 4.2.16 on 2024-12-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_user_id_savedproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproduct',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
